services:
  # PostgreSQL Database (your existing settings)
  db:
    image: postgres:15
    container_name: coachgpt-db
    restart: always
    environment:
      POSTGRES_USER: coach
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coachgpt
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - coachgpt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coach"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: coachgpt-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5002
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: coachgpt
      DB_USER: coach
      DB_PASSWORD: secret
      JWT_SECRET: coachgpt_secret_4231
      CORS_ORIGIN: http://localhost:3001
    ports:
      - "5003:5002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - coachgpt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: coachgpt-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - coachgpt-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  coachgpt-network:
    driver: bridge