version: '3.9'
services:
  db:
    image: postgres:15
    container_name: coachgpt-db
    restart: always
    environment:
      POSTGRES_USER: coach
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: coachgpt
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
