version: '3.8'

services:
  # PostgreSQL Database - For Backend only
  postgres:
    image: postgres:15-alpine
    container_name: coachgpt_db
    environment:
      POSTGRES_DB: coachgpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGUSER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API Service - INDEPENDENT (Only uses Database)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: coachgpt_backend
    environment:
      - NODE_ENV=production
      - PORT=5002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=coachgpt
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=coachgpt_secret_4231
      # Optional: LLM service URL for future integration (no dependency)
      - LLM_SERVICE_URL=http://llm-service:5003
    ports:
      - "5002:5002"
    depends_on:
      # Backend only depends on its database
      postgres:
        condition: service_healthy
      # NO dependency on redis or llm-service!
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Ollama LLM Engine - INDEPENDENT
  ollama:
    image: ollama/ollama:latest
    container_name: coachgpt_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - coachgpt_network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # LLM Microservice - SIMPLIFIED (No Database/Redis)
  llm-service:
    build:
      context: ./LLM
      dockerfile: Dockerfile
    container_name: coachgpt_llm_service
    environment:
      - NODE_ENV=production
      - PORT=5003
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      
      # LLM-specific settings only
      - LOG_LEVEL=info
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=10
      - DEFAULT_TEMPERATURE=0.7
      - DEFAULT_TOP_P=0.9
      - DEFAULT_MAX_TOKENS=200
      - LLM_TIMEOUT=70000              # 70 seconds
      
      # Remove all database/redis environment variables
      
    ports:
      - "5003:5003"
    depends_on:
      # LLM service only depends on Ollama
      ollama:
        condition: service_healthy
      # NO dependency on postgres or redis!
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    restart: unless-stopped

networks:
  coachgpt_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local