version: '3.8'

services:
  # PostgreSQL Database - For Backend only
  postgres:
    image: postgres:15-alpine
    container_name: coachgpt_db
    environment:
      POSTGRES_DB: coachgpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust 
      PGUSER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API Service 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coachgpt_backend
    environment:
      - NODE_ENV=production
      - PORT=5002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=coachgpt
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=coachgpt_secret_4231
    ports:
      - "5002:5002"
    depends_on:
      # Backend only depends on its database
      postgres:
        condition: service_healthy
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Ollama LLM Engine 
  ollama:
    image: ollama/ollama:latest
    container_name: coachgpt_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - coachgpt_network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # LLM Microservice 
  llm-service:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: coachgpt_llm_service
    environment:
      - NODE_ENV=production
      - PORT=5003
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      
      # LLM-specific settings only
      - LOG_LEVEL=info
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=10
      - DEFAULT_TEMPERATURE=0.7
      - DEFAULT_TOP_P=0.9
      - DEFAULT_MAX_TOKENS=200
      - LLM_TIMEOUT=70000              # 70 seconds
            
    ports:
      - "5003:5003"
    depends_on:
      # LLM service only depends on Ollama
      ollama:
        condition: service_healthy
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    restart: unless-stopped

  # Frontend React Application 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coachgpt_frontend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_BACKEND_URL=http://localhost:5002
      - REACT_APP_LLM_URL=http://localhost:5003
      - TSC_COMPILE_ON_ERROR=true
      - ESLINT_NO_DEV_ERRORS=true
      - DISABLE_ESLINT_PLUGIN=true
      - GENERATE_SOURCEMAP=false
      - FAST_REFRESH=true
      - SKIP_PREFLIGHT_CHECK=true
    ports:
      - "3001:3001"
    depends_on:
      # Frontend depends on backend and LLM service being healthy
      backend:
        condition: service_healthy
      llm-service:
        condition: service_healthy
    networks:
      - coachgpt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  coachgpt_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local